server:
    port: 8085
spring:
    dubbo:
        application:
            name: consumer-user
        protocol:
            name: dubbo
        registry:
            address: 'zookeeper://192.168.50.32:2181 '
        scan: com.consumer.controller
